### ISSUE TITLE
cant get this to work at all

### ISSUE THREAD

**Issue by instahater** [johnnyapol/RootMyValet#12] opened 2014-05-30 00:35 UTC
hey guys im a little new to this i have download the rootmyvalet.apk and tryed to run it and its telling me an IOExeption has occurred did you push roothandler binary to /data/local/tmp ect... can someone please give me a hand with this

**Comment by elliot-huffman** [comment] 2014-05-30 11:42
The APK is bugged. It will be worked on after the installsu.sh script is fixed. For now manually run the commands yourself.

**Comment by instahater** [comment] 2014-05-30 16:10
i have got all files to push i cant seem to find the Su binary to push also

**Comment by elliot-huffman** [comment] 2014-05-30 16:57
You have to download the SU bin your self. It is not in the source because of unknown licensing reasons. We still have to research it.

**Comment by instahater** [comment] 2014-05-30 17:00
where would i be able to get it from?

**Comment by instahater** [comment] 2014-05-30 17:00
oh i got ya!

**Comment by elliot-huffman** [comment] 2014-05-30 17:02
I get mine from here:
http://androidsu.com/superuser/
Just make sure that you are getting the right arch type

**Comment by instahater** [comment] 2014-05-30 17:13
now when i find it would i push the zip or unzip and push

**Comment by elliot-huffman** [comment] 2014-05-30 17:13
???

On Fri, May 30, 2014 at 1:13 PM, instahater notifications@github.com
wrote:

> now when i find it would i push the zip or unzip and push
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44675388
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-05-30 17:14
https://github.com/gavinlin/su-binary 
im not sure what files to push

**Comment by instahater** [comment] 2014-05-30 17:15
would it just be one file that need pushed and the site you gave me none of the links work

**Comment by elliot-huffman** [comment] 2014-05-30 17:16
Those files are for the source code so you can mod it to your liking. Try
the link that I gave you earlier

On Fri, May 30, 2014 at 1:15 PM, instahater notifications@github.com
wrote:

> would it just be one file that need pushed and the site you gave me none
> of the links work
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44675628
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-05-30 17:17
i have tryed the link but when i click to download it takes me to a yahoo error page

**Comment by elliot-huffman** [comment] 2014-05-30 17:20
Same for me... I guess we will have to wait until he fixes his links :(

On Fri, May 30, 2014 at 1:17 PM, instahater notifications@github.com
wrote:

> i have tryed the link but when i click to download it takes me to a yahoo
> error page
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44675856
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-05-30 17:20
Booo!! lol thanks bud for all your help!!

**Comment by elliot-huffman** [comment] 2014-05-30 17:21
I can give you my copy if you wish

On Fri, May 30, 2014 at 1:20 PM, instahater notifications@github.com
wrote:

> Booo!! lol thanks bud for all your help!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44676239
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by elliot-huffman** [comment] 2014-05-30 17:21
it is for ARM devices

On Fri, May 30, 2014 at 1:21 PM, Elliot Huffman thelich2@gmail.com wrote:

> I can give you my copy if you wish
> 
> On Fri, May 30, 2014 at 1:20 PM, instahater notifications@github.com
> wrote:
> 
> > Booo!! lol thanks bud for all your help!!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44676239
> > .
> 
> ## 
> 
> Elliot
> 
> DISCLAIMER:
> This e-mail is for the intended recipient(s) only
> 
> If you have received it by mistake please let me know by reply and then
> delete it from your system; access, disclosure, copying, distribution or
> reliance on any of it by anyone else is prohibited.
> 
> If you as intended recipient have received this e-mail incorrectly, please
> notify the sender (via e-mail) immediately.

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-05-30 17:22
yeah armV7

**Comment by elliot-huffman** [comment] 2014-05-30 17:23
I have to boot up my ZTE real quick... (it is on there)

On Fri, May 30, 2014 at 1:22 PM, instahater notifications@github.com
wrote:

> yeah armV7
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44676363
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-05-30 17:23
ARMv7 processor rev 1 
cores 1
mat freq 1008 mhz
instruction set arneabi-v7a,armeabi
simd NEON

**Comment by elliot-huffman** [comment] 2014-05-30 17:25
You might want to take your email off of the system. You could get
spammed... :-P

On Fri, May 30, 2014 at 1:23 PM, instahater notifications@github.com
wrote:

> you can send it to instahater@yahoo.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44676584
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-05-30 17:25
lol

**Comment by johnnyapol** [comment] 2014-05-31 15:35
I'm going to test a few changes this weekend. I apologize for the inactivity on the project, I have been finishing up school so things have been really difficult the past month getting everything together and finding free time to code in. I just finished finals, so my free time is gradually starting to return.

**Comment by elliot-huffman** [comment] 2014-06-01 18:14
There is an updated installsu.sh file. See if it works for you.

**Comment by instahater** [comment] 2014-06-01 21:30
ok i have all files pushed and configed just not sure what to do at this point

**Comment by elliot-huffman** [comment] 2014-06-01 22:01
Are you reading the wiki?

On Sun, Jun 1, 2014 at 5:30 PM, instahater notifications@github.com wrote:

> ok i have all files pushed and configed just not sure what to do at this
> point
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44789990
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-06-01 22:05
https://github.com/Unkn0wn0ne/RootMyValet/wiki   ???

**Comment by elliot-huffman** [comment] 2014-06-01 22:08
Yes, That is it! I wrote it based on the existing materials. Tell me if the
manual installation page solves your proub!

On Sun, Jun 1, 2014 at 6:05 PM, instahater notifications@github.com wrote:

> https://github.com/Unkn0wn0ne/RootMyValet/wiki ???
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44790838
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-06-01 22:19
i have dont all steps in manual and nothing.... 
and the automatic install i get this...
![capturedroid](https://cloud.githubusercontent.com/assets/6954420/3142912/cd76bbf6-e9da-11e3-9d4c-752f2d4dda64.JPG)

**Comment by instahater** [comment] 2014-06-01 22:20
- i have done*

**Comment by elliot-huffman** [comment] 2014-06-01 22:45
oh, Sorry,

I will update the manual instructions :-P Those are for installing the APK
(and that is easy)

I will add the method for rooting your device manually.

Sorry about that :-P

**Comment by elliot-huffman** [comment] 2014-06-01 22:46
Where is push.sh from? I thought that that was removed from the
instructions a while back... Instead of push.sh it is installsu.sh...

On Sun, Jun 1, 2014 at 6:45 PM, Elliot Huffman thelich2@gmail.com wrote:

> oh, Sorry,
> 
> I will update the manual instructions :-P Those are for installing the APK
> (and that is easy)
> 
> I will add the method for rooting your device manually.
> 
> Sorry about that :-P

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-06-01 22:50
I'm not sure but I will edit the batch and change it to installsu.sh... I will let you know how it turns out

**Comment by instahater** [comment] 2014-06-01 22:51
Sounds good ty

**Comment by elliot-huffman** [comment] 2014-06-01 23:07
It is edited...

On Sun, Jun 1, 2014 at 6:51 PM, instahater notifications@github.com wrote:

> Sounds good ty
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unkn0wn0ne/RootMyValet/issues/12#issuecomment-44791909
> .

## 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by instahater** [comment] 2014-06-02 00:59
ok next error lol...
![capturedroid2](https://cloud.githubusercontent.com/assets/6954420/3143275/16c79c92-e9f1-11e3-8713-0c89d1657319.JPG)

**Comment by instahater** [comment] 2014-06-02 01:13
ok i done it the wiki way with no kind of errors and didnt root so i rebooted as stated and still no good :( the error in the screen shot is a typo on my side....
![capturedroid3](https://cloud.githubusercontent.com/assets/6954420/3143308/2784dd2c-e9f3-11e3-9db8-137a7176902f.JPG)

**Comment by elliot-huffman** [comment] 2014-06-02 01:55
I will have to take a look at that again. Thanks for the screen shots. They
help a lot! I will get the batch file updated asap

**Comment by elliot-huffman** [comment] 2014-06-02 01:57
Nvm I thought you were running the batch... Currently the app (apk) does
not work. We are working on a fix for it. I am going to update the wiki so
it is more clear and has more methods in case one fails. Good night,

**Comment by johnnyapol** [comment] 2014-06-02 23:26
Closed by ff6a8a5

**Closed as completed by johnnyapol** 2014-06-02 23:26 UTC
Labels: bug
